version: '2'

services:
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: phpmyadmin
#        links:
#            - "mysql:db"
#        ports:
#            - "8080:80"
    php:
        image: koolserve/php:latest
        #image: koolserve/php:devel
        container_name: php
        restart: always
        links:
            - "mysql:mysql"
            - "redis:redis"
            - "smtp:smtp"
        depends_on:
            - mysql
        volumes:
            - /docker/www:/var/www/html
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        links:
            - "php:php"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /docker/nginx/sites-enabled:/etc/nginx/sites-enabled
            - /docker/nginx/snippets:/etc/nginx/snippets
            - /docker/www:/var/www/html
            - /docker/logs/nginx:/var/log/nginx
    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        volumes:
            - /docker/redis:/data
    mysql:
        image: percona:latest
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD='true'
        volumes:
            - /docker/mysql:/var/lib/mysql
    smtp:
        image: namshi/smtp:latest
        container_name: smtp
        restart: always
        hostname: ${HOSTNAME}
