version: '2'

services:
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: phpmyadmin
#        links:
#            - "mysql:db"
#        ports:
#            - "8080:80"
    php:
        image: koolserve/php:latest
        #image: koolserve/php:devel
        container_name: php
        restart: always
        links:
            - "mysql:mysql"
            - "redis:redis"
        depends_on:
            - nginx
            - mysql
        volumes:
            - /docker/www:/var/www/html
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /docker/nginx:/etc/nginx
            - /docker/www:/var/www/html
            - /docker/logs/nginx:/var/log/nginx
    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        volumes:
            - /docker/redis:/data
    mysql:
        image: percona:latest
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "3306:3306"
        volumes:
            - /docker/mysql:/var/lib/mysql
